version: '3.9'

services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    build:
      context: ./postgres/
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 20

  web:
    container_name: web
    env_file:
      - .env
    build:
      context: ./django/
    volumes:
      - ./django/:/usr/src/app/
    expose:
      - ${DJANGO_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 443:443
    volumes:
      - ./static:/home/app/static/
    depends_on:
      - web

volumes:
  db:
