version: '3.9'

services:
  postgres:
    build:
      context: ./postgres/
    container_name: postgres
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data

  web:
    container_name: web
    build:
      context: ./django/
    volumes:
      - static:/usr/src/app/static/
      - ./django/:/usr/src/app/
    expose:
      - ${DJANGO_PORT}
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 443:443
    volumes:
      - static:/home/app/static/
    depends_on:
      - web

volumes:
  static:
  db:
