services:
  web:
    build:
      context: ./django/
    volumes:
      - ./django/:/usr/src/app/
      - static:/usr/src/app/static/
    command: gunicorn transcande.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env/dev.env
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static:/home/app/static/
volumes:
  static:
