version: '3.9'

services:
  postgres:
    build:
      context: ./postgres/
    container_name: postgres
    env_file:
      - ./postgres/env/postgres.env
    expose:
      - 5432
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
    # restart: always
  web:
    container_name: web
    build:
      context: ./django/
    volumes:
      - static:/usr/src/app/static/
      - ./django/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./django/env/dev.env
    depends_on:
      - postgres
    # restart: always
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 443:443
    volumes:
      - static:/home/app/static/
    depends_on:
      - web
    # restart: always
volumes:
  static:
