version: '3.9'

services:
  postgres:
    restart: unless-stopped
    image: postgres:16.2-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    networks:
      - transcendence_network

  web:
    restart: unless-stopped
    container_name: web
    env_file:
      - .env
    build:
      context: ./django/
    volumes:
      - ./django/:/usr/src/app/
      - ./media/:/usr/src/app/media/
    expose:
      - ${DJANGO_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - transcendence_network

  nginx:
    restart: unless-stopped
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./static/:/var/www/static/
      - ./media/:/var/www/media/
    depends_on:
      - web
    networks:
      - transcendence_network

  redis:
    restart: unless-stopped
    container_name: redis
    image: redis:7.2.4-alpine
    volumes:
      - static:/data
    expose:
      - ${REDIS_PORT}
    networks:
      - transcendence_network

volumes:
  static:
  db:

networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge