version: '3.7'
services:
  web:
    container_name: web
    build:
      context: ./django/
    volumes:
      - ./django/:/usr/src/app/
      - static:/usr/src/app/static/
    command: gunicorn transcande.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env/dev.env
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static:/home/app/static/
    depends_on:
      - web
    restart: always
volumes:
  static:
